version: '3'
services:
    node:
        image: node:6.10
        container_name: node_fullstack_testing
        ports:
          - 4200:4200
        volumes:
          - ./angular:/var/www/html
        working_dir: /var/www/html
        tty: true
    php:
        build: docker/php7-fpm
        container_name: php7_fullstack_testing
        volumes:
           - project-data:/var/www/html
        environment:
           XDEBUG_CONFIG: remote_host=${XDEBUG_HOST} remote_enable=1 remote_port=9000 idekey=XDEBUG_SESSION_START
    nginx:
        image: nginx:1.12
        container_name: nginx_fullstack_testing
        ports:
          - 80:80
        depends_on:
          - php
        volumes:
          - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/mysite.template
          - project-data:/var/www/html
          - ./.logs:/var/log/nginx
        working_dir: /var/www/html
        environment:
          - NGINX_HOST=${NGINX_HOST}
          - NGINX_ROOT_PATH=/var/www/html/web
        command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_ROOT_PATH' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
volumes:
  project-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${SYMFONY_APP_PATH}
